set nocompatible
filetype off

"
" Vundle
"

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
call vundle#end()

"
" Plugin Settings
"
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'papercolor'

let g:ctrlp_extensions = ['tag', 'buffertag']
let g:ctrlp_max_files = 0
let g:ctrlp_clear_cache_on_exit = 0

filetype plugin indent on

"
" General Settings
"

syntax enable
syntax on

set t_Co=256          " colors
set encoding=utf8     " encoding
set ffs=unix,dos,mac  " line endings

set hidden            " don't close buffers when we leave them
set nobackup          " no ~ files
set nowb              " no write buffer
set noswapfile        " no swap file
set splitright        " split vertical to right
set splitbelow        " split horizontal to below

set expandtab         " expand tabs to spaces
set shiftwidth=4      " 4 character spaces
set tabstop=4         " 4 character tab stops

set incsearch         " show matches while typing
set hlsearch          " highlight search matches
set ignorecase        " search case insensitive
set smartcase         " but not if pattern has upper case characters

set wrap!

"
" Shortcuts
"

inoremap jk <Esc>

map <leader>pt :NERDTreeToggle<cr>

let g:ctrlp_cmd = 'CtrlPMixed'
map <c-r> :CtrlPBufTag<cr>
map <c-t> :CtrlPTag<cr>

map <leader>o o <Esc>dlo<Esc>k$a
map <leader>O O <Esc>dlO<Esc>j$a
map <leader>n o<Esc>
map <leader>N O<Esc>

map <leader>h :help 

map <leader>e :edit <c-r>=expand("%:p:h")<cr>/
map <leader>cd :cd %:p:h<cr>:pwd<cr>

"
" Load Vim Configuration for Projects
"

set exrc
set secure
